/*---------------- CONSTANT VALUE DECLERATION SECTION START ----------------------*/

const monthNames = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sept",
  "Oct",
  "Nov",
  "Dec",
];

const dayName = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

const PI = Math.PI;

/*--------------- CONSTANT VALUE DECLERATION SECTION END --------------------------*/

/*--------------- DIGITAL CLOCK SECTION START HERE -------------------------------- */

function printDate() {
  //get date from system.
  let date = new Date();
  let hh = date.getHours();
  let mm = date.getMinutes();
  let ss = date.getSeconds();
  let year = date.getFullYear();
  let month = date.getMonth();
  let day = date.getDate();
  let dayname = date.getDay();
  //checking if time/date is less than zeor for adding leading zero
  hh = check(hh);
  mm = check(mm);
  ss = check(ss);
  day = check(day);
  //formatin the date-time
  let dateResult =
    day + "-" + monthNames[month] + "-" + year + " (" + dayName[dayname] + ") ";
  let timeResult = hh + " : " + mm + " : " + ss;
  //adding to html
  doc("Date").innerText = dateResult;
  doc("Time").innerText = timeResult;
}

//Adding leading zero if any number is less than 10.
function check(val) {
  val = (val < 10 ? "0" : "") + val;
  return val;
}

window.setInterval(function () {
  printDate();
}, 1000);

/*----------------- DIGITAL CLOCK SECTION ENDS HERE --------------------*/

/*----------------- CIRCLE CIRCUMFRANCE CALCULATION SECTION STARTS HERE --------------------*/

function CircleCalculator() {
  let radius = parseFloat(doc("RadiusInput").value);
  if (isNaN(radius)) {
    console.log("nan");
    setTimeout(function () {
      doc("RadiusInput").placeholder = "Re-Enter the Radius";
    }, 1000);
    doc("RadiusInput").value = "";
    doc("RadiusInput").placeholder = "Enter valid Number";
    doc("circumfrance").innerText = "";
    doc("area").innerHTML = "";
    doc("radius").innerText = "";
  } else {
    let area = PI * radius * radius;
    let circumfrance = 2 * PI * radius;
    doc("radius").innerText = CeilFloor(radius) + " cm";
    doc("circumfrance").innerText = CeilFloor(circumfrance) + " cm";
    doc("area").innerHTML = CeilFloor(area) + " cm" + `<sup>2</sup>`;
  }
}

/*----------------- CIRCLE CIRCUMFRAMCE CALCULATION SECTION ENDS HERE --------------------*/

/*----------------- TIPS CALCULATION SECTION STARTS HERE --------------------*/
function TipsCalculator() {
  let totalAmount = parseFloat(doc("TotalAmount").value);
  let tipsPercentage = parseFloat(doc("TipsPercentage").value);
  let boolTotalAmount = !isNaN(totalAmount);
  let boolTipsPercentage = !isNaN(tipsPercentage);
  let a = doc("totalAmount");
  let b = doc("tipsPercentage");
  let r = doc("tipsResult");
  let amount = doc("TotalAmount");
  let percentage = doc("TipsPercentage");

  if (boolTotalAmount && boolTipsPercentage) {
    a.innerText = "Rs. " + CeilFloor(totalAmount);
    b.innerText = CeilFloor(tipsPercentage) + "%";
    r.innerText = "Rs. " + CeilFloor(totalAmount * (tipsPercentage / 100));
  } else if (boolTotalAmount && !boolTipsPercentage) {
    a.innerText = "Rs. " + CeilFloor(totalAmount);
    b.innerText = "";
    percentage.value = "";
    r.innerText = "";
  } else if (!boolTotalAmount && boolTipsPercentage) {
    b.innerText = CeilFloor(tipsPercentage) + "%";
    a.innerText = "";
    r.innerText = "";
    amount.value = "";
  } else {
    a.innerText = "";
    b.innerText = "";
    r.innerText = "";
  }
}
/*----------------- TIPS CALCULATION SECTION ENDS HERE --------------------*/

/*----------------- ARRAY MANIPULATION SECTION START HERE --------------------*/
function ArrayManipulation() {
  setTimeout(function () {
    alert("Open the Console!!!");
  }, 2);
  setTimeout(function () {
    let arrayLength = 5;
    let array = [];
    const noOfMove = 20 + RandomNumberGenerator(21);
    for (let i = 0; i < arrayLength; i++) {
      array.push(
        GenerateRandomString(5 + (parseInt(Math.random() * 100) % 10))
      );
    }

    console.log("-----> Lets Check you are Lucky or UnLucky");
    console.log(
      "-----> We have an randomly generated String array of length " +
        arrayLength
    );
    console.log(array);
    console.log("-----> And we have 2 random number generator engine A & B");
    console.log("-----> Engine A generate number between [0 to array.length) ");
    console.log("-----> And Engine B generate number either 0 or 1. ");
    console.log(
      "-----> If B generate '0' than computer will remove the element of array at index=(value generated by A)"
    );
    console.log(
      "-----> Otherwise add the randomly generated element at index=(value generated by A)"
    );

    console.log("-----> Number of moves is also remdomly generated");
    console.log(
      "-----> Minimum moves you got is 20 and maximum move you got is 40"
    );
    console.log("-----> You got " + noOfMove + " moves");
    console.log(
      "-----> Within " +
        noOfMove +
        " moves if the lenght of array is zero i.e. (array is empty) than you are Lucky otherwise NOT!!"
    );
    console.log("-----> Lets Start");
    let ok = true;
    console.log(array);
    for (let i = 0; i < noOfMove; i++) {
      hold();
      console.log(
        "<--------------------- " + (i + 1) + " steps ------------------->"
      );
      arrayLength = array.length;
      if (arrayLength == 0) {
        console.log("-----> Length of array is " + arrayLength);
        console.log("-----> You Are Lucky");
        ok = false;
        break;
      }
      let A_val = RandomNumberGenerator(arrayLength);
      let B_val = RandomNumberGenerator(2);
      console.log("-----> Engine A generage => " + A_val);
      let brr = [];
      if (B_val == 1) {
        //push()
        console.log("-----> Engine B generate => " + B_val + " (push)");
        let ramdomString = GenerateRandomString(
          5 + (parseInt(Math.random() * 100) % 10)
        );
        for (let j = 0; j < arrayLength; j++) {
          if (j == A_val) {
            brr.push(ramdomString);
          }
          brr.push(array[j]);
        }
        console.log(
          '-----> Lets push ramdomly generated string "' +
            ramdomString +
            '" at index ' +
            A_val
        );
        if (i == noOfMove - 1) {
          arrayLength++;
        }
      } else {
        //pop()
        console.log("-----> Engine B generate => " + B_val + " (pop)");
        for (let j = 0; j < array.length; j++) {
          if (j != A_val) brr.push(array[j]);
        }
        console.log(
          '-----> Lets pop "' + array[A_val] + '" from index ' + A_val
        );
        if (i == noOfMove - 1) {
          arrayLength--;
        }
      }
      array = brr;
      console.log("-----> New Array is");
      console.log(array);
    }
    if (ok) {
      console.log("-----> Length of Array is " + arrayLength);
      console.log("-----> You Are UnLucky");
    }
  }, 5000);
  console.log("------------------ Wait for 5 second-----------------");
}

/*----------------- ARRAY MANIPULATION SECTION START HERE --------------------*/

/*----------------- THIRD PARTY FUNCTION START HERE --------------------------------- */

function hold() {
  for (let i = 0; i < 800000000; i++) {}
}

function RandomNumberGenerator(mod) {
  return parseInt(Math.random() * 10000000) % mod;
}
function GenerateRandomString(length) {
  const char = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  let resultString = "";
  for (let i = 0; i < length; i++) {
    let rand = parseInt(Math.random() * 100);
    resultString += char[rand % 26];
  }
  return resultString;
}

function CeilFloor(val) {
  console.log(Math.ceil(val), Math.floor(val));
  console.log("Hello");
  return Math.floor(val.toFixed(2)) == Math.ceil(val.toFixed(2))
    ? parseInt(val)
    : val.toFixed(2);
}

function doc(val) {
  return document.getElementById(val);
}
/*----------------- THIRD PARTY FUNCTION ENDS HERE -----------------------------------*/
